INSERT INTO STATION(NAME) VALUES ('Marienplatz');
INSERT INTO STATION(NAME) VALUES ('Holzkirchen');
INSERT INTO STATION(NAME) VALUES ('Peterhausen');
INSERT INTO STATION(NAME) VALUES ('Leuchtenbergring');
INSERT INTO STATION(NAME) VALUES ('Geltendorf');
INSERT INTO STATION(NAME) VALUES ('Ebersberg');
INSERT INTO STATION(NAME) VALUES ('Herrsching');
INSERT INTO STATION(NAME) VALUES ('Erding');
INSERT INTO STATION(NAME) VALUES ('Tutzing');
INSERT INTO STATION(NAME) VALUES ('Kreuzstrasse');
INSERT INTO STATION(NAME) VALUES ('Wolfratzhausen');

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('W', 'S5', 'S5 W WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Ebersberg', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Herrsching', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('E', 'S5', 'S5 E WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Herrsching', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Ebersberg', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('W', 'S2', 'S2 W WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Holzkirchen', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Peterhausen', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('E', 'S2', 'S2 E WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Peterhausen', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S2 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Holzkirchen', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('W', 'S4', 'S4 W WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Leuchtenbergring', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Geltendorf', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('E', 'S4', 'S4 E WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Geltendorf', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S4 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Leuchtenbergring', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('W', 'S6', 'S6 W WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Erding', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Tutzing', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('E', 'S6', 'S6 E WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Tutzing', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S6 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Erding', 20);


INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('W', 'S7', 'S7 W WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Kreuzstrasse', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Wolfratzhausen', 20);

INSERT INTO ROUTE (DIRECTION, LINE_NAME, NAME) VALUES ('E', 'S7', 'S7 E WEEKDAY');
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Wolfratzhausen', 0);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', 10);
INSERT INTO ROUTE_PLAN(ROUTE_ID, STATION_ID, ORDER_NUM) VALUES (SELECT ID FROM ROUTE WHERE NAME='S7 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Kreuzstrasse', 20);



INSERT INTO SCHEDULE(ID, ROUTE_ID, TRAIN_ID, ORDER_NUM) VALUES (1, SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', 734, 0);
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (1, SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Ebersberg', NULL, '5:03:00');
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (1, SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', '5:33:00', '5:33:15');
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (1, SELECT ID FROM ROUTE WHERE NAME='S5 W WEEKDAY', SELECT ID FROM STATION WHERE NAME='Herrsching', '6:03:00', NULL);

INSERT INTO SCHEDULE(ID, ROUTE_ID, TRAIN_ID, ORDER_NUM) VALUES (2, SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', 734, 0);
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (2, SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Herrsching', NULL, '6:33:00');
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (2, SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Marienplatz', '7:03:00', '7:03:15');
INSERT INTO SCHEDULED_STOP(SCHEDULE_ID, ROUTE_ID, STATION_ID, ARRIVES, DEPARTS) VALUES (2, SELECT ID FROM ROUTE WHERE NAME='S5 E WEEKDAY', SELECT ID FROM STATION WHERE NAME='Ebersberg', '7:33:00', NULL);
