CREATE TABLE STATION(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ROUTE(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  DIRECTION VARCHAR(255) NOT NULL,
  LINE_NAME VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);

/*
mirrors route
there can (and will) be multiple schedules per route
there can be multiple entries for train and route (trains run more than once a day)
*/
CREATE TABLE SCHEDULE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ROUTE_ID INT NOT NULL,
  TRAIN_ID INT NOT NULL,
  ORDER_NUM INT NOT NULL,
  FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ID)
);


CREATE TABLE ROUTE_PLAN (
  ROUTE_ID INT NOT NULL,
  STATION_ID INT NOT NULL,
  ORDER_NUM INT NOT NULL,
  FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ID),
  FOREIGN KEY(STATION_ID) REFERENCES STATION(ID),
  PRIMARY KEY(ROUTE_ID, STATION_ID, ORDER_NUM)
);



/*
mirrors route_plan, with arrival/departure times
there can (and will) be multiple schedules per route
there can be multiple entries for train and route (trains run more than once a day)
*/

CREATE TABLE SCHEDULED_STOP (
  SCHEDULE_ID INT NOT NULL,
  ROUTE_ID INT NOT NULL,
  STATION_ID INT NOT NULL,
  ARRIVES VARCHAR(255) NULL,
  DEPARTS VARCHAR(255) NULL,
  FOREIGN KEY(SCHEDULE_ID) REFERENCES SCHEDULE(ID),
  FOREIGN KEY(STATION_ID) REFERENCES STATION(ID),
  FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ID)
);